/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createPartnerRec = /* GraphQL */ `
  mutation CreatePartnerRec($input: PartnerMInput!) {
    createPartnerRec(input: $input) {
      PK
      PK1
      PK2
      PK3
      SK
      SK1
      SK2
      SK3
      gid
      id
      minMaxRange {
        minprice
        maxprice
        minarea
        maxarea
      }
      itemType
      orgName
      orgLegalName
      orgShortName
      orgSlug
      orgContactDetails
      orgAddressDetails
      orgBusinessDetails
      orgBrandDetails
      orgStatus
      orgAggregates
      isVerifiedOrg
      projName
      projShortName
      projSlug
      projDescription
      projContactDetails
      projCategory
      propertyCategories
      tags
      projBrandDetails
      projStatus
      projAggregates
      projLaunchDate
      projCompletedDate
      authorities
      projGeoDataReference
      projConfiguration
      projAddress
      projArea
      photos
      videos
      views360
      virtualTours
      tlTales
      documents
      pricingConfig
      subscriptionLevel
      projVisibility
      zoneName
      zoneShortName
      zoneSlug
      zoneLaunchDate
      zoneVisibility
      plotName
      plotSlug
      plotGeoDataReference
      plotStatus
      plotAreaDetails
      plotBasePrice
      plotPrice
      plotFacing
      plotConfiguration
      plotLatestTransaction
      ownershipType
      ownershipPercentage
      enquiryDate
      enquiryDesc
      enquiryFirstName
      enquiryLastName
      enquiryPhone
      enquiryEmail
      enquiryConsentDeatils
      enquiryStatus
      enquiryType
      userFirstName
      userLaststName
      userEmail
      userPhone
      userVisibility
      userCognitoID
      userConsentDeatils
    }
  }
`;
export const updatePartnerRec = /* GraphQL */ `
  mutation UpdatePartnerRec($input: PartnerMInput!) {
    updatePartnerRec(input: $input) {
      PK
      PK1
      PK2
      PK3
      SK
      SK1
      SK2
      SK3
      gid
      id
      minMaxRange {
        minprice
        maxprice
        minarea
        maxarea
      }
      itemType
      orgName
      orgLegalName
      orgShortName
      orgSlug
      orgContactDetails
      orgAddressDetails
      orgBusinessDetails
      orgBrandDetails
      orgStatus
      orgAggregates
      isVerifiedOrg
      projName
      projShortName
      projSlug
      projDescription
      projContactDetails
      projCategory
      propertyCategories
      tags
      projBrandDetails
      projStatus
      projAggregates
      projLaunchDate
      projCompletedDate
      authorities
      projGeoDataReference
      projConfiguration
      projAddress
      projArea
      photos
      videos
      views360
      virtualTours
      tlTales
      documents
      pricingConfig
      subscriptionLevel
      projVisibility
      zoneName
      zoneShortName
      zoneSlug
      zoneLaunchDate
      zoneVisibility
      plotName
      plotSlug
      plotGeoDataReference
      plotStatus
      plotAreaDetails
      plotBasePrice
      plotPrice
      plotFacing
      plotConfiguration
      plotLatestTransaction
      ownershipType
      ownershipPercentage
      enquiryDate
      enquiryDesc
      enquiryFirstName
      enquiryLastName
      enquiryPhone
      enquiryEmail
      enquiryConsentDeatils
      enquiryStatus
      enquiryType
      userFirstName
      userLaststName
      userEmail
      userPhone
      userVisibility
      userCognitoID
      userConsentDeatils
    }
  }
`;
export const deletePartnerRec = /* GraphQL */ `
  mutation DeletePartnerRec($input: PartnerMDelInput!) {
    deletePartnerRec(input: $input) {
      PK
      PK1
      PK2
      PK3
      SK
      SK1
      SK2
      SK3
      gid
      id
      minMaxRange {
        minprice
        maxprice
        minarea
        maxarea
      }
      itemType
      orgName
      orgLegalName
      orgShortName
      orgSlug
      orgContactDetails
      orgAddressDetails
      orgBusinessDetails
      orgBrandDetails
      orgStatus
      orgAggregates
      isVerifiedOrg
      projName
      projShortName
      projSlug
      projDescription
      projContactDetails
      projCategory
      propertyCategories
      tags
      projBrandDetails
      projStatus
      projAggregates
      projLaunchDate
      projCompletedDate
      authorities
      projGeoDataReference
      projConfiguration
      projAddress
      projArea
      photos
      videos
      views360
      virtualTours
      tlTales
      documents
      pricingConfig
      subscriptionLevel
      projVisibility
      zoneName
      zoneShortName
      zoneSlug
      zoneLaunchDate
      zoneVisibility
      plotName
      plotSlug
      plotGeoDataReference
      plotStatus
      plotAreaDetails
      plotBasePrice
      plotPrice
      plotFacing
      plotConfiguration
      plotLatestTransaction
      ownershipType
      ownershipPercentage
      enquiryDate
      enquiryDesc
      enquiryFirstName
      enquiryLastName
      enquiryPhone
      enquiryEmail
      enquiryConsentDeatils
      enquiryStatus
      enquiryType
      userFirstName
      userLaststName
      userEmail
      userPhone
      userVisibility
      userCognitoID
      userConsentDeatils
    }
  }
`;
